name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo "running build"
        docker build -f docker/Dockerfile -t maticnetwork/heimdall:mat-3270 .
        echo "pushing image"
        docker push maticnetwork/heimdall:mat-3270
        echo "DONE!"
