name: Linux package

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Retrieve release version
        run: echo "::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\/v/}"

      - name: Build package
        run: |
          set -x

          sudo apt-get -yqq install libpq-dev build-essential
          gem install --no-document fpm
          fpm --version

          make install
          mkdir -p build
          export GOBIN=$(go env GOPATH)/bin
          cp -rf $GOBIN/* build/

          cat > heimdalld.service <<- "EOF"
          [Unit]
          Description=heimdall
          [Service]
          WorkingDirectory=/usr/bin/
          ExecStartPre=/bin/mkdir -p /var/log/matic-logs/
          ExecStart=/bin/bash -c '/usr/bin/heimdalld start --home /etc/heimdall/ > /var/log/matic-logs/heimdalld.log 2>&1'
          Type=simple
          User=root
          EOF

          cat > heimdalld-bridge.service <<- "EOF"
          [Unit]
          Description=heimdall-bridge
          [Service]
          WorkingDirectory=/usr/bin/
          ExecStartPre=/bin/mkdir -p /var/log/matic-logs/
          ExecStart=/bin/bash -c "/usr/bin/bridge start --all --home /etc/heimdall/ > /var/log/matic-logs/heimdalld-bridge.log 2>&1"
          Type=simple
          User=root
          EOF

          cat > heimdalld-rest-server.service <<- "EOF"
          [Unit]
          Description=heimdalld-rest-server
          [Service]
          WorkingDirectory=/usr/bin/
          ExecStartPre=/bin/mkdir -p /var/log/matic-logs/
          ExecStart=/bin/bash -c "/usr/bin/heimdalld rest-server --home /etc/heimdall/ > /var/log/matic-logs/heimdalld-rest-server.log 2>&1"
          Type=simple
          User=root
          EOF

          cat > after_install.sh <<- "EOF"
          #!/bin/bash
          mkdir -p /etc/heimdall/
          echo alias heimdalld='"sudo heimdalld --home /etc/heimdall"' >> ~/.bashrc
          echo alias heimdallcli='"sudo heimdallcli --home /etc/heimdall"' >> ~/.bashrc
          source ~/.bashrc
          EOF

          fpm -s dir -t deb --deb-user root --deb-group root -n matic-heimdall -v ${{ env.RELEASE_VERSION }} --config-files heimdalld.service \
            --after-install after_install.sh \
            heimdalld.service=/etc/systemd/system/ \
            heimdalld-rest-server.service heimdalld-rest-server.service=/etc/systemd/system/ \
            heimdalld-bridge.service heimdalld-bridge.service=/etc/systemd/system/ \
            build/bridge=/usr/bin/ \
            build/heimdallcli=/usr/bin/ \
            build/heimdalld=/usr/bin/ 

          mkdir packages-v${{ env.RELEASE_VERSION }}

          mv matic-heimdall_${{ env.RELEASE_VERSION }}_amd64.deb packages-v${{ env.RELEASE_VERSION }}/

          ls packages-v${{ env.RELEASE_VERSION }}/

      - name: S3 upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "packages-v${{ env.RELEASE_VERSION }}"
          DEST_DIR: "v${{ env.RELEASE_VERSION }}"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: code-releases
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "New linux package for Heimdall v${{ env.RELEASE_VERSION }} just got released"
          SLACK_MESSAGE: "Package has been uploaded to S3 bucket for public use and available at https://matic-public.s3.amazonaws.com/v${{ env.RELEASE_VERSION }}/matic-heimdall_${{ env.RELEASE_VERSION }}_amd64.deb"
